[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = espidf
monitor_speed = 115200
upload_speed = 921600

build_flags = 
    -D CORE_DEBUG_LEVEL=3
    -D CONFIG_LWIP_SO_REUSE=1
    -Wno-format
    -Wno-type-limits

lib_deps = 

board_build.filesystem = littlefs